
name: 'google_ads_demo'
version: '0.1'
config-version: 2
profile: 'google_ads_demo'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"
vars:
  google_ads_schema: google_ads_demo
  google_ads_database: pc_fivetran_db

models:
  google_ads_demo: 
      materialized: table
      staging:
        materialized: view
        tags: ["staging", "hourly"]
